track:
  name: Barber Motorsports Park
  location: Birmingham, Alabama
  country: USA

geometry:
  length_m: 3830.0  # 3.83 km / 2.38 mi official length
  width_m: 13.72    # ~45 ft track width
  direction: clockwise
  turns: 17
  elevation_change_m: 24.4  # ~80 ft elevation change

svg:
  source: barber.svg
  auto_detect: true
  override_length: null  # null = use auto-detection, or set to override

ribbons:
  per_side: 5           # 5 ribbons on each side (11 total with center)
  max_offset_m: 6.86    # Half of track width (13.72m / 2)
  join_style: round     # round, mitre, or bevel
  quad_segs: 12         # Smoothness of round joins

car_assignments: {}
  # Car ID: ribbon name mapping
  # Leave empty ({}) for auto-assignment
  # Example:
  # "010": "left_1.37m"
  # "002": "right_1.37m"

processing:
  svg_samples_per_seg: 4000
  centerline_points: 5000
  smoothing: 0.0  # 0 = exact interpolation, > 0 = smoothing
